version: '3'

services:
  webserver:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - 8080:80
  db:
    image: mariadb:10.5
    privileged: true
    environment:
      - MYSQL_USER=ivrank
      - MYSQL_PASSWORD=poopboobs
      - MYSQL_DATABASE=ivrank
      - MYSQL_ROOT_PASSWORD=poopboobs
    ports:
      - 3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
